name: megalopolis
description: Megalopolis
version: 1.0.0
environment:
  sdk: ^3.10.4
dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.0
  shared_preferences: ^2.2.2
  permission_handler: ^12.0.1
  qr_code_scanner: ^1.0.1
  flutter_riverpod: ^2.6.1
  flutter_animate: ^4.3.0
  carousel_slider: ^5.1.1
  pin_code_fields: ^8.0.1
  path_provider: ^2.1.1
  dotted_border: ^3.1.0
  google_fonts: ^6.1.0
  url_launcher: ^6.2.2
  image_picker: ^1.0.5
  flutter_map: ^8.2.2
  geolocator: ^14.0.2
  flutter_svg: ^2.0.9
  qr_flutter: ^4.1.0
  go_router: ^17.0.1
  latlong2: ^0.9.0
  sqflite: ^2.3.0
  shimmer: ^3.0.0
  badges: ^3.1.2
  lottie: ^3.3.2
  fl_chart: ^1.1.1
  uuid: ^4.2.2
  intl: ^0.20.2
  path: ^1.8.3
flutter:
  uses-material-design: true